# Generated by Django 5.2.4 on 2026-09-12 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_mistpart_breakdownhistory_msa_mistinspection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.RemoveField(
            model_name='msa',
            name='part',
        ),
        migrations.RemoveField(
            model_name='mistinspection',
            name='msa',
        ),
        migrations.AlterModelOptions(
            name='breakdown',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='breakdownhistory',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='machine',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='mistinspection',
            options={'ordering': ['-inspected_at']},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='machine',
            name='display_order',
        ),
        migrations.AddField(
            model_name='breakdown',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_breakdowns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='breakdown',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=20),
        ),
        migrations.AddField(
            model_name='breakdown',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='breakdownhistory',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='breakdown_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='machine',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mistinspection',
            name='inspected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mist_inspections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='status',
            field=models.CharField(choices=[('ON', 'ON'), ('OFF', 'OFF'), ('MAINTENANCE', 'Maintenance')], default='OFF', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('category', 'name'), name='unique_section_per_category'),
        ),
        migrations.AddField(
            model_name='machinestatuslog',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machine_status_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='machinestatuslog',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='maintenance.machine'),
        ),
        migrations.DeleteModel(
            name='MISTPart',
        ),
        migrations.DeleteModel(
            name='MSA',
        ),
    ]
